#!/bin/bash

tar -C /usr/share/X11/ -czf xkb-sicherung.tgz xkb/symbols/{de,level3,level5,shift} xkb/rules/{base,base.xml,evdev,evdev.xml} xkb/types/level5

# wget -c http://neo-layout.org/xkb.tgz
# tar -C /usr/share/X11/ -xzf xkb.tgz

cp de /usr/share/X11/xkb/symbols/de

# Doing this also screws up the busybox keymap in Debian (testing, jessie).
# cp keyboard /etc/default/keyboard
