#!/bin/bash

dpkg-divert --quiet --local --divert /usr/share/X11/xkb/symbols/de_org --rename /usr/share/X11/xkb/symbols/de
cp de /usr/share/X11/xkb/symbols/de

# Doing this also screws up the busybox keymap in Debian (jessie).
# cp keyboard /etc/default/keyboard
