#!/bin/bash

ls --almost-all -1 |grep --perl-regexp --invert-match '^(.git$|\w|.htoprc)'|while read file; do
    target="$PWD/$file"
    target=${target#$HOME/}
    ln --symbolic --no-target-directory "$target" "$HOME/$file"
done

ln --symbolic --no-target-directory ../../Projekte/dotfiles/.htoprc "$HOME/.config/htop/htoprc"
