#!/bin/bash

cd "`dirname "$0"`"
git submodule update --init --recursive

vim_spell=".vim/spell"
mkdir --parents "$vim_spell"
for file in {en,de}.utf-8.{spl,sug};do
    if [ ! -e "$vim_spell/$file" ];then
        wget --continue "ftp://ftp.vim.org/pub/vim/runtime/spell/$file" --output-document="$vim_spell/$file"
    fi
done

## does not work:
# vim -c ":set rtp=.vim,.vim/bundle/vundle"

vim -c ':BundleInstall' -c ':q' -c ':q' -u .vimrc

# Improves performance of ZSH. Functions not needed or not used (yet).
pushd .oh-my-zsh/lib/
rm aliases.zsh bzr.zsh correction.zsh grep.zsh key-bindings.zsh misc.zsh nvm.zsh rbenv.zsh rvm.zsh spectrum.zsh termsupport.zsh functions.zsh

# git commit -am 'Improves performance of ZSH. Functions not needed or not used (yet).'
# Leave submodule dirty.
popd
