#!/bin/bash

cd "$(dirname "$0")"
git submodule update --init --recursive

vim_spell=".vim/spell"
mkdir --parents "$vim_spell"
for file in {en,de}.utf-8.{spl,sug};do
    if [ ! -e "$vim_spell/$file" ];then
        wget --continue "http//ftp.vim.org/pub/vim/runtime/spell/$file" --output-document="$vim_spell/$file"
    fi
done

## Legacy. Needed on Debian wheezy system.
wget --continue "http//ftp.vim.org/pub/vim/runtime/spell/de.latin1.spl" --output-document="$vim_spell/de.latin1.spl"

## Improves performance of ZSH. Functions not needed or not used (yet).
## Leave submodule dirty.
pushd .oh-my-zsh/lib/
rm bzr.zsh correction.zsh grep.zsh key-bindings.zsh misc.zsh nvm.zsh spectrum.zsh termsupport.zsh functions.zsh
popd
