#!/bin/bash

cd "`dirname "$0"`"
git submodule update --init --recursive

ls --almost-all -1 |grep --perl-regexp --invert-match '^(.git$|\w|.htoprc)'|while read file; do
    target="$PWD/$file"
    target=${target#$HOME/}
    ln --symbolic --no-target-directory "$target" "$HOME/$file"
done

ln --symbolic --no-target-directory ../../Projekte/dotfiles/.htoprc "$HOME/.config/htop/htoprc"

# inside another submodule …
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/Schnouki/git-annex-zsh-completion.git ~/.oh-my-zsh/custom/plugins/git-annex

vim_spell="$HOME/.vim/spell"
mkdir --parents "$vim_spell"
for file in {en,de}.utf-8.{spl,sug};do
    if [ ! -e "$vim_spell/$file" ];then
        wget --continue "ftp://ftp.vim.org/pub/vim/runtime/spell/$file" --output-document="$vim_spell/$file"
    fi
done

vi -c ':BundleInstall' -c ':q' -c ':q'

# Improves performance of ZSH. Functions not needed or not used (yet).
pushd .oh-my-zsh/lib/
rm aliases.zsh bzr.zsh correction.zsh grep.zsh key-bindings.zsh misc.zsh nvm.zsh rbenv.zsh rvm.zsh spectrum.zsh termsupport.zsh functions.zsh

# git commit -am 'Improves performance of ZSH. Functions not needed or not used (yet).'
# Leave submodule dirty.
popd
