#!/bin/bash
# Sourced by Bash and zsh.

# Functions which might be called by other sourced shell scripts.

# https://superuser.com/questions/39751/add-directory-to-path-if-its-not-already-there/753948#753948
pathprepend() {
  for ARG in "$@"
  do
    ARG="${ARG%/}"
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="$ARG${PATH:+":$PATH"}"
    fi
  done
}

pathappend() {
  for ARG in "$@"
  do
    ARG="${ARG%/}"
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="${PATH:+"$PATH:"}$ARG"
    fi
  done
}

# https://gist.github.com/florianbeer/ee02c149a7e25f643491
ssh() {
    if [ "$(ps -p "$(ps -p $$ -o ppid= | sed 's/\s//g;')" -o comm=)" = "tmux" ]; then
        tmux rename-window "$(echo "$@" | rev | cut -d ' ' -f1 | rev | cut -d . -f 1)"
        command ssh "$@"
        tmux set-window-option automatic-rename "on" 1>/dev/null
    else
        echo -ne "\033]0;$(echo "$@" | rev | cut -d ' ' -f1 | rev)\007"
        command ssh "$@"
        echo -ne "\033]0;Terminal\007"
    fi
}
