#!/bin/sh
# Sourced by Bash and zsh.

if [ -e "${XDG_CONFIG_HOME:-$HOME/.config}/shell.d" ]
then
	## Damn. Not all distribution have run-parts available … (openSUSE 13.1)
	# run-parts --list "${XDG_CONFIG_HOME:-$HOME/.config}/shell.d" | while read file
	find "${XDG_CONFIG_HOME:-$HOME/.config}/shell.d" -type f -or -type l | sort | while read -r file
	do
		# shellcheck source=/dev/null
		. "$file"
	done
fi
