#!/bin/bash
# shellcheck disable=SC2139
# .. vim: foldmarker={{{,}}}:foldmethod=marker

if [ -n "$ANDROID_ROOT" ]; then
    cd || exit
fi

## Exports {{{

## https://superuser.com/questions/479600/how-can-i-prevent-tmux-exiting-with-ctrl-d
# export IGNOREEOF=2
## Does not work with zsh

export INPUTRC="${XDG_CONFIG_HOME}/readline/inputrc"
export ANSIBLE_NOCOWS=1
export BYOBU_PREFIX="/usr"
export BYOBU_CONFIG_DIR="$HOME/.byobu"
export EDITOR=vim

export LANG='en_US.UTF-8'
export LANGUAGE='en_US:en'

if [ -z "$ANDROID_ROOT" ]; then
    # http://terokarvinen.com/international_iso-8601_date_on_thunderbird.html
    export LC_TIME='en_DK.UTF-8'
fi

## https://www.suse.com/releasenotes/i386/openSUSE/11.1/RELEASE-NOTES.en.html#04
export MAN_POSIXLY_CORRECT=1

## }}}

## Enable color support of ls and also add handy aliases {{{
if command -v dircolors >/dev/null 2>&1; then
    export LS_OPTIONS='--color=auto'
    eval "$(dircolors)"
    alias ls='ls --color=auto --human-readable --time-style=long-iso'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

## }}}

## Little functions {{{
function up {
    if [[ $1 =~ ^-?[0-9]+$ ]]
    then
        local ups=""
        # shellcheck disable=SC2034
        for fnord in $(seq 1 "$1")
        do
            ups="${ups}../"
        done
        cd "$ups" || exit 1
    elif [ -z "$1" ]; then
        cd ..
    fi
}

## Create a new directory and enter it.
unalias md 2>/dev/zero
function md() {
    mkdir -p "$@"
    cd "$@" || return
}

function virsh-disks() {
    virsh --quiet domblklist "$1" --details | grep '^block' | while read -r line; do
        disk_path="${line##* }"; info="$(lsblk "$disk_path" --output NAME,SIZE,TYPE --noheadings --nodeps)"
        echo "$info $line"
    done
}

function run-c() {
    echo "main(){ ${*} }" | tcc -run -
}

function subnetcalc() {
    if [[ $# == 0 ]]; then
        /usr/bin/subnetcalc
    else
        /usr/bin/subnetcalc "$@" -n
    fi
}

## https://gist.github.com/CMCDragonkai/62c04977f62037285772
function sed-keyword-escape {
    echo "$1" | sed -e 's/[]\/$*.^|[]/\\&/g'
}

function sed-replace-escape {
    echo "$1" | sed -e 's/[\/&]/\\&/g'
}

function sed-easy {
    sed -i "s/$(sed-keyword-escape "$1")/$(sed-replace-escape "$2")/g" "$3"
}

function h {
    pattern="${1:-.}"

    if [[ "$pattern" == "." ]]; then
        history
    else
        history | egrep -e "$pattern"
    fi
}

## }}}

## Shell basics {{{

alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

## }}}

## Editor {{{

## On Debian this is provided by the alternatives systems.
if ! command -v editor >/dev/null 2>&1
then
    alias editor="$EDITOR"
fi

alias e='editor'
alias ,e='exit'
alias ,x='exit'
alias ,r='editor'
# alias less='vim -c "w! /tmp/.vimpager" -'

## }}}

## SSH {{{

alias ssh='ssh_wrapper ssh'
alias sshrc='ssh_wrapper sshrc'
alias s='ssh'
alias i='sshrc'
alias so='assh sockets'
alias sk='assh sockets flush'

ssh_default="-F /etc/ssh/ssh_config -o \"UserKnownHostsFile=$HOME/.ssh/known_hosts_tmp\""
# Should work now without this hack.
#
alias rsync-default="rsync -e \"ssh $ssh_default\""
alias ssh-default="ssh $ssh_default"
alias scp-default="scp $ssh_default"
# alias ssh-copy-id='ssh-copy-id -o PubkeyAuthentication=no'
alias sshfs='sshfs -o transform_symlinks'
alias sshfs-default='sshfs -o transform_symlinks -F /etc/ssh/ssh_config'
alias ssh-keygen-sec='ssh-keygen -o -b 8192 -a 200 -t rsa'

## }}}

## Git {{{
export GITHUB_USER="ypid"
# Used in https://github.com/ypid/scripts/blob/master/git-setup-and-push-to-my-fork

## Able to push to all git remotes with the one command?
## http://stackoverflow.com/a/18674313
alias gpa='git pa'

## Use the shortcuts from oh-my-zsh for git
alias wd='git diff --color-words --no-index'

# Define important shortcuts here if under bash (are already defended by oh-my-zsh) {{{
alias g='git'

alias ga='git add'
alias gst='git status'

## Does not distinguish between changed files and changed/dirty submodules and it looks terrible …
# alias gst='git status --short --branch'

alias gco='git checkout'
alias gc='git commit --verbose'
alias gca='gc --all'
alias gb='git branch'

function n() {
    git log --reverse --pretty=%H master | grep -A 1 "$(git rev-parse HEAD)" | tail -n1 | xargs git checkout
}
function p() {
    git checkout HEAD^1
}

## }}}

# Overwrite alias from oh-my-zsh {{{
alias glg='git log --stat --decorate=short --show-signature' # full history
# alias glg='tig --show-signature' # full history

## }}}

## }}}

## asdf {{{
# shellcheck source=/dev/null
test -f "${ASDF_DIR}/completions/asdf.bash" && source "${ASDF_DIR}/completions/asdf.bash"
command -v asdf >/dev/null 2>&1 && alias m='asdf'
## }}}

## GnuPG {{{
alias gpg-check-debian-iso='gpg --no-default-keyring --keyring /usr/share/keyrings/debian-role-keys.gpg --verify'
alias gpg-sign='gpg --default-key 489A4D5EC353C98A --armor --detach-sig'

if command -v qubes-gpg-client >/dev/null 2>&1; then
    command -v compdef >/dev/null 2>&1 && compdef qubes-gpg-client=gpg
fi
if command -v qubes-gpg-client-wrapper >/dev/null 2>&1; then
    alias k=qubes-gpg-client-wrapper
    command -v compdef >/dev/null 2>&1 && compdef qubes-gpg-client-wrapper=gpg
else
    alias k=gpg
fi
## }}}

## ag {{{
if command -v ag >/dev/null 2>&1
then
    ## Using silversearcher-ag
    alias ack='ag'
elif command -v ack-grep >/dev/null 2>&1
then
    alias ack='ack-grep'
fi
# }}}

## Package management {{{

if [ -e "${PREFIX:-}/etc/apt" ]; then
    alias m='apt'
    alias ai='apt install'
    alias ap='apt purge'
    alias as='\apt search'
    alias ash='\apt show'
    alias an='apt update && apt upgrade'
elif [ -e "${PREFIX:-}/etc/zypp" ]; then
    alias m='zypper'
    alias ai='zypper install'
    alias ap='zypper remove'
    alias as='zypper search'
    alias ash='zypper info'
    alias an='zypper update'
fi

# }}}

## More aliases {{{

if [ -z "$ANDROID_ROOT" ]; then
    alias tmux='TERM=screen-256color-bce tmux'
fi

alias d='docker'
alias t='task'
alias '*'='dict'
alias con='ping heise.de'
alias a='git-annex'
alias v='vagrant'
alias jj='zpool'
alias dotup='~/.config/dotfiles/install'
alias meminfo=$'awk \'$3=="kB"{$2=$2/1024;$3="MB"} 1\' /proc/meminfo | column -t'

## Ping on steroids. This was the last time that some messed up M$ host tricked me because it refused to answer echo requests.
alias al='nmap -n --reason -sP'

# if command -v nping >/dev/null 2>&1
# then
#     alias ping='nping'
# fi

if ! command -v hd >/dev/null 2>&1
then
    alias hd='hexdump -C'
fi

# http://stackoverflow.com/questions/16787916/difference-between-2-directories-in-linux
alias diff-dir='diff -arq'

alias percent-encode='python -c "import urllib, sys; print urllib.quote(sys.argv[1])"'
alias percent-decode='python -c "import urllib, sys; print urllib.unquote(sys.argv[1])"'

alias badblocks='echo "Use badblocks_and_secure_erase."'

if [[ "$USER" != 'root' ]] && [ -z "$ANDROID_ROOT" ]; then
    alias mount='sudo mount'
    alias umount='sudo umount'
    alias smount='sudo smount'
    alias sumount='sudo sumount'
    alias aptitude='sudo aptitude'
    alias apt='sudo apt'
    alias zypper='sudo zypper'
    alias sc='sudo ~root/.local/share/scripts/ypid-scripts-common/sc'
fi

alias rpm-keys="rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'"

alias xclip-primary-to-clipboard='xclip -out | xclip -in -selection clipboard'

## Use as needed. --show-nonprinting does also output Unicode glyphs in escaped form.
# alias cat='cat --show-nonprinting'

alias bc='bc -q'
alias ,='popd'

## https://tools.ietf.org/html/rfc3339
alias ts='date --rfc-3339=seconds'

## }}}

## Ignore typos {{{
alias 6s='ls'
alias sl='ls'
alias fgfg='fg'
## }}}
