#!/bin/sh
# Sourced by Bash and zsh.

# SPDX-FileCopyrightText: 2022 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

if [ -e /etc/update-motd.d ]; then
    run-parts /etc/update-motd.d
else
    cat /etc/motd
fi

# Show who else is logged in.
w --no-header | grep -v "^$USER" || :
