#!/bin/sh
# Sourced by Bash and zsh.

# SPDX-FileCopyrightText: 2022 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

test -e /etc/update-motd.d && run-parts /etc/update-motd.d
test -e /etc/motd && cat /etc/motd

# Show who else is logged in.
w --no-header | grep -v "^$USER" || :
