# Do not repeat default values here.
k9s:
  ui:
    enableMouse: true
    # Skin cannot be set per cluster currently.
    # Ref: https://github.com/derailed/k9s/issues/1487
    # skin: everforest-dark # Looks relaxing.
    # skin: kanagawa # Close to everforest-dark otherwise good.
    # skin: narsingh # Plain but nice.
    # skin: nightfox
    # skin: red # Default to scary looking skin representing Prod to force users overwrite this per cluster.
    # skin: solarized-16
    skin: solarized-light
    # skin: in_the_navy
  skipLatestRevCheck: true
  shellPod:
    image: busybox
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
